import type {
  Company,
  Approval,
  ActivityEntry,
  Thread,
  Agent,
  AgentRole,
  PRDSection,
  InspirationCard,
  Human,
  Pipeline,
  Issue,
  Memory,
  StreamItem,
  Skill,
  BrandGuide,
  SOP,
} from "./types";

// ───── Agents (reusable templates) ─────
const mkCEO = (id: string): Agent => ({
  id,
  role: "CEO · Strategist",
  shortRole: "CEO",
  roleColor: "brass",
  name: "CEO Agent",
  model: "Opus 4.7",
  provider: "anthropic",
  status: "working",
  todayCost: 12.4,
  lifetimeCost: 482.1,
  skills: ["strategy", "delegation", "bilingual-es-en", "daniel-taste-pack"],
  persona: "Senior founder-operator. Challenges assumptions. Bilingual ES/EN.",
});

const mkFrontend = (id: string): Agent => ({
  id,
  role: "Frontend Engineer",
  shortRole: "FE",
  roleColor: "teal",
  name: "Frontend Agent",
  model: "Claude Code · Sonnet",
  provider: "anthropic",
  status: "working",
  todayCost: 8.1,
  lifetimeCost: 214.4,
  skills: ["react-19", "nextjs-15", "tailwind-4", "responsive"],
  persona: "Senior frontend dev. Ships responsive, accessible components.",
});

const mkBackend = (id: string): Agent => ({
  id,
  role: "Backend Engineer",
  shortRole: "BE",
  roleColor: "teal",
  name: "Backend Agent",
  model: "Codex · GPT-5.4",
  provider: "openai",
  status: "idle",
  todayCost: 5.2,
  lifetimeCost: 198.6,
  skills: ["node", "postgres", "api-design", "auth-patterns"],
  persona: "Backend architect. Type-safe by default. Async-first.",
});

const mkDevOps = (id: string): Agent => ({
  id,
  role: "DevOps",
  shortRole: "OPS",
  roleColor: "success",
  name: "DevOps Agent",
  model: "Sonnet · GitHub App",
  provider: "anthropic",
  status: "idle",
  todayCost: 1.8,
  lifetimeCost: 48.2,
  skills: ["ci-cd", "vercel", "cloudflare", "monitoring"],
  persona: "Infra steward. No credentials in code, ever.",
});

const mkQA = (id: string): Agent => ({
  id,
  role: "QA Reviewer",
  shortRole: "QA",
  roleColor: "danger",
  name: "QA Agent",
  model: "Codex · Playwright",
  provider: "openai",
  status: "working",
  todayCost: 4.4,
  lifetimeCost: 132.1,
  skills: ["playwright", "e2e-testing", "accessibility"],
  persona: "Test every button. Report every break.",
});

const mkSecurity = (id: string): Agent => ({
  id,
  role: "Security Advisor",
  shortRole: "SEC",
  roleColor: "warning",
  name: "Security Agent",
  model: "Opus · read-only",
  provider: "anthropic",
  status: "idle",
  todayCost: 0.8,
  lifetimeCost: 22.4,
  skills: ["threat-modeling", "owasp", "secrets-hygiene"],
  persona: "Read-only. Flags risk before it ships.",
});

const mkSEO = (id: string): Agent => ({
  id,
  role: "SEO Specialist",
  shortRole: "SEO",
  roleColor: "teal",
  name: "SEO Agent",
  model: "Sonnet",
  provider: "anthropic",
  status: "idle",
  todayCost: 0.4,
  lifetimeCost: 12.8,
  skills: ["technical-seo", "content-strategy", "keyword-research"],
  persona: "Audit every page. Recommend, don't rewrite.",
});

const mkMarketing = (id: string): Agent => ({
  id,
  role: "Marketing Agent",
  shortRole: "M",
  roleColor: "success",
  name: "Marketing Agent",
  model: "Sonnet",
  provider: "anthropic",
  status: "working",
  todayCost: 3.1,
  lifetimeCost: 86.4,
  skills: ["copywriting-es-en", "brand-voice", "local-seo"],
  persona: "Writes in Daniel's brand voice. Bilingual.",
});

const mkConcierge = (id: string, name: string): Agent => ({
  id,
  role: name,
  shortRole: name === "Guest Concierge" ? "G" : "H",
  roleColor: "success",
  name,
  model: "Sonnet",
  provider: "anthropic",
  status: "working",
  todayCost: 0.6,
  lifetimeCost: 18.4,
  skills: ["hospitality", "bilingual-es-en", "airbnb-messaging"],
  persona: "Warm, professional, replies in <90s.",
});

// ───── Humans ─────
const salvador: Human = {
  id: "salvador",
  name: "Salvador",
  role: "Full-stack developer",
  status: "online",
  initials: "S",
};

const daniel: Human = {
  id: "daniel",
  name: "Daniel (you)",
  role: "Chairman",
  status: "online",
  initials: "DT",
};

// ───── Pipelines ─────
const legacyProfilerPipeline: Pipeline = {
  id: "p-lt-profiler-v3",
  featureName: "Bryan AI — Profiler v3 (trader risk profiles)",
  startedAt: "2026-04-16T09:00:00Z",
  ownerAgentId: "lt-ceo",
  prNumber: 247,
  currentPhaseIndex: 3,
  progressPercent: 55,
  phases: [
    {
      name: "explore",
      displayName: "Explore",
      status: "done",
      assignedAgentId: "lt-ceo",
      assignedLabel: "CEO · Opus",
      durationLabel: "✓ completed in 8m · 14 turns",
      startedAt: "2026-04-16T09:00:00Z",
      completedAt: "2026-04-16T09:08:00Z",
      turnsUsed: 14,
      cost: 0.34,
      artifacts: [
        { id: "p1-e-1", type: "doc", name: "codebase-analysis.md", size: "2.4k tokens" },
        { id: "p1-e-2", type: "doc", name: "engram-context-load.md", size: "1.1k tokens" },
        { id: "p1-e-3", type: "report", name: "risk-scoring-prior-art.md", size: "0.8k tokens" },
      ],
      handoffNote: "Handoff to Propose phase: 3 viable approaches identified (Kelly, Sharpe, modified Sharpe)",
    },
    {
      name: "propose",
      displayName: "Propose",
      status: "done",
      assignedAgentId: "lt-ceo",
      assignedLabel: "CEO · Opus",
      durationLabel: "✓ completed in 12m 41s · 22 turns",
      startedAt: "2026-04-16T09:08:00Z",
      completedAt: "2026-04-16T09:21:00Z",
      turnsUsed: 22,
      cost: 0.18,
      artifacts: [
        { id: "p1-p-1", type: "doc", name: "proposal.md", size: "3 alternatives considered" },
        { id: "p1-p-2", type: "doc", name: "trade-off-matrix.md", size: "1.8k tokens" },
        { id: "p1-p-3", type: "report", name: "kelly-vs-sharpe-benchmark.md", size: "2.1k tokens" },
      ],
      handoffNote: "Handoff to Spec phase: modified Sharpe selected · Daniel approved direction",
    },
    {
      name: "spec",
      displayName: "Spec",
      status: "done",
      assignedAgentId: "lt-be",
      assignedLabel: "Architect · Sonnet",
      durationLabel: "✓ completed in 6m · reviewed by Salvador",
      startedAt: "2026-04-16T09:21:00Z",
      completedAt: "2026-04-16T09:27:00Z",
      turnsUsed: 18,
      cost: 0.45,
      artifacts: [
        { id: "p1-s-1", type: "spec", name: "spec.md", size: "3 acceptance criteria" },
        { id: "p1-s-2", type: "doc", name: "input-output-contract.md", size: "1.4k tokens" },
        { id: "p1-s-3", type: "doc", name: "edge-cases.md", size: "9 cases enumerated" },
        { id: "p1-s-4", type: "report", name: "risk-assessment.md", size: "1.2k tokens" },
      ],
      handoffNote: "Handoff to Design phase: reviewed by Salvador ✓",
    },
    {
      name: "design",
      displayName: "Design",
      status: "active",
      assignedAgentId: "lt-ceo",
      assignedLabel: "Opus 4.7",
      durationLabel: "● running 3m · 7 turns so far",
      startedAt: "2026-04-18T11:42:00Z",
      turnsUsed: 7,
      cost: 0.62,
      artifacts: [
        { id: "p1-d-1", type: "design", name: "architecture-diagram.md", size: "draft" },
        { id: "p1-d-2", type: "doc", name: "ADR-004-modified-sharpe.md", size: "in progress" },
        { id: "p1-d-3", type: "design", name: "module-boundaries.md", size: "0.6k tokens" },
      ],
    },
    {
      name: "implement",
      displayName: "Implement",
      status: "pending",
      assignedLabel: "FE + BE",
      durationLabel: "queued",
      cost: 0,
      artifacts: [],
    },
    {
      name: "verify",
      displayName: "Verify",
      status: "pending",
      assignedLabel: "QA · Playwright",
      durationLabel: "queued",
      cost: 0,
      artifacts: [],
    },
    {
      name: "archive",
      displayName: "Archive",
      status: "pending",
      assignedLabel: "Docs",
      durationLabel: "—",
      cost: 0,
      artifacts: [],
    },
  ],
  events: [
    {
      id: "p1-ev-1",
      type: "phase_started",
      phaseId: "explore",
      agentId: "lt-ceo",
      timestamp: "2026-04-16T09:00:00Z",
      description: "Explore phase kicked off · loading Engram context",
    },
    {
      id: "p1-ev-2",
      type: "phase_completed",
      phaseId: "explore",
      agentId: "lt-ceo",
      timestamp: "2026-04-16T09:08:00Z",
      description: "Explore complete · 3 viable risk-scoring approaches surfaced",
    },
    {
      id: "p1-ev-3",
      type: "handoff",
      phaseId: "propose",
      agentId: "lt-ceo",
      timestamp: "2026-04-16T09:08:30Z",
      description: "Handoff Explore → Propose · CEO retains ownership",
    },
    {
      id: "p1-ev-4",
      type: "review_approved",
      phaseId: "propose",
      timestamp: "2026-04-16T09:20:00Z",
      description: "Daniel approved direction: modified Sharpe over Kelly",
    },
    {
      id: "p1-ev-5",
      type: "phase_completed",
      phaseId: "propose",
      agentId: "lt-ceo",
      timestamp: "2026-04-16T09:21:00Z",
      description: "Propose complete · proposal.md saved to Engram",
    },
    {
      id: "p1-ev-6",
      type: "handoff",
      phaseId: "spec",
      agentId: "lt-be",
      timestamp: "2026-04-16T09:21:30Z",
      description: "Handoff Propose → Spec · Architect agent assigned",
    },
    {
      id: "p1-ev-7",
      type: "review_approved",
      phaseId: "spec",
      timestamp: "2026-04-16T09:26:00Z",
      description: "Salvador reviewed spec.md · 3 ACs accepted",
    },
    {
      id: "p1-ev-8",
      type: "phase_completed",
      phaseId: "spec",
      agentId: "lt-be",
      timestamp: "2026-04-16T09:27:00Z",
      description: "Spec complete · contract + edge cases documented",
    },
    {
      id: "p1-ev-9",
      type: "handoff",
      phaseId: "design",
      agentId: "lt-ceo",
      timestamp: "2026-04-18T11:42:00Z",
      description: "Handoff Spec → Design · Opus 4.7 picking up architecture",
    },
    {
      id: "p1-ev-10",
      type: "phase_started",
      phaseId: "design",
      agentId: "lt-ceo",
      timestamp: "2026-04-18T11:42:00Z",
      description: "Design phase started · drafting ADR-004",
    },
  ],
};

const legacyDashboardPipeline: Pipeline = {
  id: "p-lt-dashboard-ws",
  featureName: "Dashboard — live P&L over WebSocket",
  startedAt: "2026-04-15T10:00:00Z",
  ownerAgentId: "lt-fe",
  prNumber: 251,
  currentPhaseIndex: 4,
  progressPercent: 66,
  phases: [
    {
      name: "explore",
      displayName: "Explore",
      status: "done",
      assignedAgentId: "lt-fe",
      assignedLabel: "FE · Sonnet",
      durationLabel: "✓ completed in 8m · 11 turns",
      startedAt: "2026-04-15T10:00:00Z",
      completedAt: "2026-04-15T10:08:00Z",
      turnsUsed: 11,
      cost: 0.21,
      artifacts: [
        { id: "p2-e-1", type: "doc", name: "websocket-codebase-scan.md", size: "1.9k tokens" },
        { id: "p2-e-2", type: "report", name: "polling-baseline-metrics.md", size: "0.7k tokens" },
        { id: "p2-e-3", type: "doc", name: "browser-compat-notes.md", size: "0.5k tokens" },
      ],
      handoffNote: "Handoff to Propose phase: WebSocket viable · Safari needs keepalive",
    },
    {
      name: "propose",
      displayName: "Propose",
      status: "done",
      assignedAgentId: "lt-fe",
      assignedLabel: "FE · Sonnet",
      durationLabel: "✓ completed in 6m · 9 turns",
      startedAt: "2026-04-15T10:08:00Z",
      completedAt: "2026-04-15T10:14:00Z",
      turnsUsed: 9,
      cost: 0.14,
      artifacts: [
        { id: "p2-p-1", type: "doc", name: "proposal.md", size: "2 alternatives considered" },
        { id: "p2-p-2", type: "doc", name: "ws-vs-sse.md", size: "1.0k tokens" },
        { id: "p2-p-3", type: "report", name: "estimated-cost-savings.md", size: "0.4k tokens" },
      ],
      handoffNote: "Handoff to Spec phase: WebSocket with SSE fallback selected",
    },
    {
      name: "spec",
      displayName: "Spec",
      status: "done",
      assignedAgentId: "lt-be",
      assignedLabel: "Architect · Sonnet",
      durationLabel: "✓ completed in 11m · reviewed by Daniel",
      startedAt: "2026-04-15T10:14:00Z",
      completedAt: "2026-04-15T10:25:00Z",
      turnsUsed: 16,
      cost: 0.38,
      artifacts: [
        { id: "p2-s-1", type: "spec", name: "spec.md", size: "4 acceptance criteria" },
        { id: "p2-s-2", type: "doc", name: "ws-protocol-contract.md", size: "1.6k tokens" },
        { id: "p2-s-3", type: "doc", name: "reconnect-strategy.md", size: "0.9k tokens" },
      ],
      handoffNote: "Handoff to Design phase: reviewed by Daniel ✓",
    },
    {
      name: "design",
      displayName: "Design",
      status: "done",
      assignedAgentId: "lt-fe",
      assignedLabel: "Sonnet",
      durationLabel: "✓ completed in 14m · 24 turns",
      startedAt: "2026-04-15T10:25:00Z",
      completedAt: "2026-04-15T10:39:00Z",
      turnsUsed: 24,
      cost: 0.86,
      artifacts: [
        { id: "p2-d-1", type: "design", name: "architecture-diagram.md", size: "1.8k tokens" },
        { id: "p2-d-2", type: "doc", name: "ADR-005-ws-fallback.md", size: "1.2k tokens" },
        { id: "p2-d-3", type: "design", name: "client-state-machine.md", size: "1.4k tokens" },
        { id: "p2-d-4", type: "doc", name: "backpressure-strategy.md", size: "0.8k tokens" },
      ],
      handoffNote: "Handoff to Implement phase: state machine signed off",
    },
    {
      name: "implement",
      displayName: "Implement",
      status: "blocked",
      assignedAgentId: "lt-fe",
      assignedLabel: "FE + BE",
      durationLabel: "⚠ blocked · awaiting your review",
      startedAt: "2026-04-15T10:39:00Z",
      turnsUsed: 41,
      cost: 2.94,
      artifacts: [
        { id: "p2-i-1", type: "code", name: "8 files changed · +412 -87 lines", size: "WIP" },
        { id: "p2-i-2", type: "report", name: "review-blocker.md", size: "auth handshake concern" },
      ],
      handoffNote: "Blocked: Backend agent flagged auth handshake concern · needs human review",
    },
    {
      name: "verify",
      displayName: "Verify",
      status: "pending",
      assignedLabel: "QA · Playwright",
      durationLabel: "queued",
      cost: 0,
      artifacts: [],
    },
    {
      name: "archive",
      displayName: "Archive",
      status: "pending",
      assignedLabel: "Docs",
      durationLabel: "—",
      cost: 0,
      artifacts: [],
    },
  ],
  events: [
    {
      id: "p2-ev-1",
      type: "phase_started",
      phaseId: "explore",
      agentId: "lt-fe",
      timestamp: "2026-04-15T10:00:00Z",
      description: "Explore kicked off · scanning WebSocket usage in dashboard",
    },
    {
      id: "p2-ev-2",
      type: "phase_completed",
      phaseId: "explore",
      agentId: "lt-fe",
      timestamp: "2026-04-15T10:08:00Z",
      description: "Explore complete · Safari WebSocket flakiness flagged from Engram",
    },
    {
      id: "p2-ev-3",
      type: "handoff",
      phaseId: "propose",
      agentId: "lt-fe",
      timestamp: "2026-04-15T10:08:30Z",
      description: "Handoff Explore → Propose · same agent (FE)",
    },
    {
      id: "p2-ev-4",
      type: "phase_completed",
      phaseId: "propose",
      agentId: "lt-fe",
      timestamp: "2026-04-15T10:14:00Z",
      description: "Propose complete · WebSocket with SSE fallback recommended",
    },
    {
      id: "p2-ev-5",
      type: "handoff",
      phaseId: "spec",
      agentId: "lt-be",
      timestamp: "2026-04-15T10:14:30Z",
      description: "Handoff Propose → Spec · Architect agent assigned",
    },
    {
      id: "p2-ev-6",
      type: "review_approved",
      phaseId: "spec",
      timestamp: "2026-04-15T10:24:00Z",
      description: "Daniel reviewed spec.md · 4 ACs accepted",
    },
    {
      id: "p2-ev-7",
      type: "phase_completed",
      phaseId: "design",
      agentId: "lt-fe",
      timestamp: "2026-04-15T10:39:00Z",
      description: "Design complete · ADR-005 saved to Engram",
    },
    {
      id: "p2-ev-8",
      type: "phase_started",
      phaseId: "implement",
      agentId: "lt-fe",
      timestamp: "2026-04-15T10:39:30Z",
      description: "Implement started · FE + BE pair on the change",
    },
    {
      id: "p2-ev-9",
      type: "commit_pushed",
      phaseId: "implement",
      agentId: "lt-fe",
      timestamp: "2026-04-15T11:10:00Z",
      description: "5 commits pushed to feature/dashboard-ws",
    },
    {
      id: "p2-ev-10",
      type: "commit_pushed",
      phaseId: "implement",
      agentId: "lt-be",
      timestamp: "2026-04-15T11:42:00Z",
      description: "3 commits pushed · auth handshake refactor",
    },
    {
      id: "p2-ev-11",
      type: "phase_started",
      phaseId: "implement",
      agentId: "lt-be",
      timestamp: "2026-04-17T14:20:00Z",
      description: "BE flagged auth handshake concern · pipeline blocked for review",
    },
  ],
};

const legacyAuthPipeline: Pipeline = {
  id: "p-lt-auth-migration",
  featureName: "Auth — Clerk → NextAuth migration",
  startedAt: "2026-04-12T09:00:00Z",
  ownerAgentId: "lt-be",
  prNumber: 248,
  currentPhaseIndex: 5,
  progressPercent: 82,
  phases: [
    {
      name: "explore",
      displayName: "Explore",
      status: "done",
      assignedAgentId: "lt-be",
      assignedLabel: "BE · GPT-5.4",
      durationLabel: "✓ completed in 10m · 16 turns",
      startedAt: "2026-04-12T09:00:00Z",
      completedAt: "2026-04-12T09:10:00Z",
      turnsUsed: 16,
      cost: 0.28,
      artifacts: [
        { id: "p3-e-1", type: "doc", name: "clerk-usage-audit.md", size: "2.7k tokens" },
        { id: "p3-e-2", type: "doc", name: "nextauth-feature-parity.md", size: "1.5k tokens" },
        { id: "p3-e-3", type: "report", name: "migration-risk-areas.md", size: "0.9k tokens" },
      ],
      handoffNote: "Handoff to Propose: 12 Clerk touchpoints identified · 3 are high-risk",
    },
    {
      name: "propose",
      displayName: "Propose",
      status: "done",
      assignedAgentId: "lt-be",
      assignedLabel: "BE · GPT-5.4",
      durationLabel: "✓ completed in 7m · 12 turns",
      startedAt: "2026-04-12T09:10:00Z",
      completedAt: "2026-04-12T09:17:00Z",
      turnsUsed: 12,
      cost: 0.16,
      artifacts: [
        { id: "p3-p-1", type: "doc", name: "proposal.md", size: "2 alternatives considered" },
        { id: "p3-p-2", type: "report", name: "rollout-strategy.md", size: "phased migration plan" },
        { id: "p3-p-3", type: "doc", name: "rollback-criteria.md", size: "0.6k tokens" },
      ],
      handoffNote: "Handoff to Spec: phased dual-write migration approved by Daniel",
    },
    {
      name: "spec",
      displayName: "Spec",
      status: "done",
      assignedAgentId: "lt-be",
      assignedLabel: "Architect · Sonnet",
      durationLabel: "✓ completed in 13m · reviewed by Daniel",
      startedAt: "2026-04-12T09:17:00Z",
      completedAt: "2026-04-12T09:30:00Z",
      turnsUsed: 19,
      cost: 0.42,
      artifacts: [
        { id: "p3-s-1", type: "spec", name: "spec.md", size: "5 acceptance criteria" },
        { id: "p3-s-2", type: "doc", name: "session-migration-contract.md", size: "1.7k tokens" },
        { id: "p3-s-3", type: "doc", name: "jwt-claims-mapping.md", size: "1.0k tokens" },
        { id: "p3-s-4", type: "report", name: "security-considerations.md", size: "1.3k tokens" },
      ],
      handoffNote: "Handoff to Design phase: reviewed by Daniel ✓",
    },
    {
      name: "design",
      displayName: "Design",
      status: "done",
      assignedAgentId: "lt-ceo",
      assignedLabel: "Opus 4.7",
      durationLabel: "✓ completed in 22m · 31 turns",
      startedAt: "2026-04-12T09:30:00Z",
      completedAt: "2026-04-12T09:52:00Z",
      turnsUsed: 31,
      cost: 1.18,
      artifacts: [
        { id: "p3-d-1", type: "design", name: "architecture-diagram.md", size: "2.4k tokens" },
        { id: "p3-d-2", type: "doc", name: "ADR-006-nextauth-adapter.md", size: "1.6k tokens" },
        { id: "p3-d-3", type: "design", name: "session-bridge-flow.md", size: "1.1k tokens" },
        { id: "p3-d-4", type: "doc", name: "feature-flag-rollout.md", size: "0.7k tokens" },
      ],
      handoffNote: "Handoff to Implement: dual-write with Clerk shadow mode",
    },
    {
      name: "implement",
      displayName: "Implement",
      status: "done",
      assignedAgentId: "lt-be",
      assignedLabel: "BE · GPT-5.4",
      durationLabel: "✓ completed in 1h 14m · 87 turns",
      startedAt: "2026-04-12T09:52:00Z",
      completedAt: "2026-04-12T11:06:00Z",
      turnsUsed: 87,
      cost: 4.62,
      artifacts: [
        { id: "p3-i-1", type: "code", name: "23 files changed · +1,247 -589 lines", size: "PR #248" },
        { id: "p3-i-2", type: "doc", name: "migration-runbook.md", size: "1.9k tokens" },
        { id: "p3-i-3", type: "report", name: "test-coverage-delta.md", size: "+18% on auth paths" },
      ],
      handoffNote: "Handoff to Verify: PR #248 ready for security scan",
    },
    {
      name: "verify",
      displayName: "Verify",
      status: "blocked",
      assignedAgentId: "lt-sec",
      assignedLabel: "Security · Opus",
      durationLabel: "⚠ blocked · 2 findings · awaiting decision",
      startedAt: "2026-04-12T11:06:00Z",
      turnsUsed: 23,
      cost: 0.74,
      artifacts: [
        { id: "p3-v-1", type: "report", name: "security-scan.md", size: "2 findings" },
        { id: "p3-v-2", type: "report", name: "finding-1-jwt-leak-vector.md", size: "high severity" },
        { id: "p3-v-3", type: "report", name: "finding-2-session-fixation.md", size: "medium severity" },
      ],
      handoffNote: "Blocked: 2 security findings · rollback executed · awaiting Daniel decision",
    },
    {
      name: "archive",
      displayName: "Archive",
      status: "pending",
      assignedLabel: "Docs",
      durationLabel: "—",
      cost: 0,
      artifacts: [],
    },
  ],
  events: [
    {
      id: "p3-ev-1",
      type: "phase_started",
      phaseId: "explore",
      agentId: "lt-be",
      timestamp: "2026-04-12T09:00:00Z",
      description: "Explore kicked off · auditing Clerk integration",
    },
    {
      id: "p3-ev-2",
      type: "phase_completed",
      phaseId: "explore",
      agentId: "lt-be",
      timestamp: "2026-04-12T09:10:00Z",
      description: "Explore complete · 12 Clerk touchpoints mapped",
    },
    {
      id: "p3-ev-3",
      type: "review_approved",
      phaseId: "propose",
      timestamp: "2026-04-12T09:16:00Z",
      description: "Daniel approved phased dual-write migration",
    },
    {
      id: "p3-ev-4",
      type: "phase_completed",
      phaseId: "propose",
      agentId: "lt-be",
      timestamp: "2026-04-12T09:17:00Z",
      description: "Propose complete · proposal.md saved to Engram",
    },
    {
      id: "p3-ev-5",
      type: "review_approved",
      phaseId: "spec",
      timestamp: "2026-04-12T09:29:00Z",
      description: "Daniel reviewed spec.md · 5 ACs accepted",
    },
    {
      id: "p3-ev-6",
      type: "handoff",
      phaseId: "design",
      agentId: "lt-ceo",
      timestamp: "2026-04-12T09:30:30Z",
      description: "Handoff Spec → Design · Opus picking up architecture",
    },
    {
      id: "p3-ev-7",
      type: "phase_completed",
      phaseId: "design",
      agentId: "lt-ceo",
      timestamp: "2026-04-12T09:52:00Z",
      description: "Design complete · ADR-006 saved · feature flag plan ready",
    },
    {
      id: "p3-ev-8",
      type: "commit_pushed",
      phaseId: "implement",
      agentId: "lt-be",
      timestamp: "2026-04-12T10:24:00Z",
      description: "12 commits pushed · NextAuth adapter scaffolded",
    },
    {
      id: "p3-ev-9",
      type: "commit_pushed",
      phaseId: "implement",
      agentId: "lt-be",
      timestamp: "2026-04-12T10:58:00Z",
      description: "11 more commits · session bridge live in shadow mode",
    },
    {
      id: "p3-ev-10",
      type: "phase_completed",
      phaseId: "implement",
      agentId: "lt-be",
      timestamp: "2026-04-12T11:06:00Z",
      description: "Implement complete · PR #248 opened",
    },
    {
      id: "p3-ev-11",
      type: "phase_started",
      phaseId: "verify",
      agentId: "lt-sec",
      timestamp: "2026-04-12T11:06:30Z",
      description: "Verify started · Security agent running scan",
    },
    {
      id: "p3-ev-12",
      type: "phase_started",
      phaseId: "verify",
      agentId: "lt-sec",
      timestamp: "2026-04-15T16:00:00Z",
      description: "Security flagged 2 findings · rollback executed · pipeline blocked",
    },
  ],
};

// ───── Issues ─────
const legacyIssues: Issue[] = [
  {
    id: "lt-247",
    code: "LT-247",
    title: "Bryan AI profiler v3 — risk score algorithm",
    subtitle: "Pipeline active · design phase · blocks 3 downstream",
    description: "Compute risk score from historical P&L + volatility metrics.",
    status: "in-progress",
    assigneeLabel: "A",
    assigneeColor: "brass",
    pipelineId: "p-lt-profiler-v3",
    costSoFar: 42.10,
    createdAt: "2026-04-16T09:00:00Z",
  },
  {
    id: "lt-251",
    code: "LT-251",
    title: "Dashboard — real-time P&L streaming",
    subtitle: "WebSocket refactor · needs your review on approach",
    description: "Move from polling to WebSocket for live P&L updates.",
    status: "review",
    assigneeLabel: "FE",
    assigneeColor: "teal",
    pipelineId: "p-lt-dashboard-ws",
    costSoFar: 18.44,
    createdAt: "2026-04-17T14:20:00Z",
  },
  {
    id: "lt-248",
    code: "LT-248",
    title: "Auth: migrate from Clerk to NextAuth",
    subtitle: "Security flagged 2 findings · rolled back",
    description: "Migration rolled back pending security review.",
    status: "blocked",
    assigneeLabel: "S",
    assigneeColor: "warning",
    pipelineId: "p-lt-auth-migration",
    costSoFar: 8.12,
    createdAt: "2026-04-15T11:00:00Z",
  },
  {
    id: "lt-245",
    code: "LT-245",
    title: "Landing page — options strategy explainer",
    subtitle: "Shipped to production · awaiting SEO audit",
    description: "New explainer page for options strategies.",
    status: "done",
    assigneeLabel: "FE",
    assigneeColor: "teal",
    costSoFar: 6.88,
    createdAt: "2026-04-14T10:00:00Z",
  },
  {
    id: "lt-252",
    code: "LT-252",
    title: "Profiler — backtest harness for Sharpe variants",
    subtitle: "Blocks LT-247 verify phase · needs historical dataset",
    description: "Wire backtest harness with 5y SPX + VIX data.",
    status: "in-progress",
    assigneeLabel: "BE",
    assigneeColor: "teal",
    pipelineId: "p-lt-profiler-v3",
    costSoFar: 9.20,
    createdAt: "2026-04-17T09:00:00Z",
  },
  {
    id: "lt-253",
    code: "LT-253",
    title: "Profiler — UI for risk tier thresholds",
    subtitle: "Queued after design phase · 3 confirmation states",
    description: "Let operator adjust risk tier thresholds via slider.",
    status: "queued",
    assigneeLabel: "FE",
    assigneeColor: "teal",
    pipelineId: "p-lt-profiler-v3",
    costSoFar: 0,
    createdAt: "2026-04-17T12:00:00Z",
  },
  {
    id: "lt-250",
    code: "LT-250",
    title: "Observability — dashboard alerting + PagerDuty",
    subtitle: "Implementation phase · writing Terraform",
    description: "Wire alerts for API latency + error rate regressions.",
    status: "in-progress",
    assigneeLabel: "OPS",
    assigneeColor: "success",
    costSoFar: 4.44,
    createdAt: "2026-04-16T15:00:00Z",
  },
  {
    id: "lt-249",
    code: "LT-249",
    title: "Checkout — Stripe 3DS edge cases",
    subtitle: "QA caught 3 drop-off paths on mobile Safari",
    description: "Handle 3DS challenge retry + rejected card flow.",
    status: "review",
    assigneeLabel: "QA",
    assigneeColor: "danger",
    costSoFar: 11.60,
    createdAt: "2026-04-16T10:30:00Z",
  },
  {
    id: "lt-244",
    code: "LT-244",
    title: "P&L chart — candle granularity preference",
    subtitle: "Ship blocker: preference persists but ignored on reload",
    description: "Fix localStorage sync race with Zustand hydration.",
    status: "in-progress",
    assigneeLabel: "FE",
    assigneeColor: "teal",
    costSoFar: 3.22,
    createdAt: "2026-04-15T14:45:00Z",
  },
  {
    id: "lt-243",
    code: "LT-243",
    title: "Broker API — Tradovate rate limit retries",
    subtitle: "429s during open · exponential backoff landed",
    description: "Implement adaptive backoff with jitter.",
    status: "done",
    assigneeLabel: "BE",
    assigneeColor: "teal",
    costSoFar: 7.88,
    createdAt: "2026-04-14T08:00:00Z",
  },
  {
    id: "lt-242",
    code: "LT-242",
    title: "SEO — structured data for options strategies",
    subtitle: "Merged · awaiting Google indexing confirmation",
    description: "Add JSON-LD Article + HowTo schema to explainer pages.",
    status: "done",
    assigneeLabel: "SEO",
    assigneeColor: "teal",
    costSoFar: 1.40,
    createdAt: "2026-04-13T11:00:00Z",
  },
  {
    id: "lt-241",
    code: "LT-241",
    title: "Onboarding — Spanish locale pass",
    subtitle: "Merged · 42 strings translated · reviewed by Daniel",
    description: "Full ES pass on onboarding flow.",
    status: "done",
    assigneeLabel: "CEO",
    assigneeColor: "brass",
    costSoFar: 2.60,
    createdAt: "2026-04-12T09:15:00Z",
  },
];

// ───── Live stream items (per company) ─────
const legacyStreamItems: StreamItem[] = [
  {
    id: "s-1",
    agentLabel: "DESIGN · OPUS",
    action: "thinking",
    timeLabel: "NOW",
    body: "Evaluating trade-offs between Kelly criterion and modified Sharpe for risk scoring. Engram has 3 prior decisions on this — loading context…",
  },
  {
    id: "s-2",
    agentLabel: "FE · SONNET",
    action: "writing",
    timeLabel: "2s",
    body: "Editing <code>components/dashboard/LiveChart.tsx</code> · WebSocket subscription refactor",
  },
  {
    id: "s-3",
    agentLabel: "QA · PLAYWRIGHT",
    action: "testing",
    timeLabel: "12s",
    body: "Running E2E suite on staging · <code>checkout.spec.ts</code> · 14/23 passed, 2 flaky, 0 failed",
  },
  {
    id: "s-4",
    agentLabel: "SALVADOR",
    action: "human commit",
    timeLabel: "4m",
    body: "Pushed 3 commits to <code>feature/profiler-v3</code> · Engram synced · your Claude will see on next pull",
  },
  {
    id: "s-5",
    agentLabel: "CEO · OPUS",
    action: "decision",
    timeLabel: "8m",
    body: "Approved spec handoff to Design phase · saved rationale to Engram as <code>sdd/profiler-v3/spec-rationale</code>",
  },
];

const emptyStream = (name: string): StreamItem[] => [
  {
    id: `${name}-s-1`,
    agentLabel: "CEO · OPUS",
    action: "idle",
    timeLabel: "12m",
    body: "No active pipelines · standing by for next briefing",
  },
];

// ───── Memories ─────
const legacyMemories: Memory[] = [
  {
    id: "m-1",
    title: "Kelly criterion vs modified Sharpe for risk scoring",
    type: "decision",
    content:
      "Chose modified Sharpe after benchmarking both on 18mo of paper-traded data. Kelly over-weighted recent drawdowns — Bryan's profile flipped between conservative/aggressive every 2 weeks. Sharpe with 90d rolling window stabilizes the score.",
    savedBy: "CEO Agent",
    createdAt: "2026-04-17T15:00:00Z",
    tags: ["profiler", "risk", "architecture"],
    pipelineRef: { id: "pl-profiler", label: "Bryan AI — Profiler v3" },
    referencedCount: 14,
    lastAccessedAt: "2026-04-18T22:00:00Z",
  },
  {
    id: "m-2",
    title: "WebSocket flakiness on Safari mobile",
    type: "bug",
    content:
      "Safari iOS 17+ drops idle WebSockets after 60s even with keepalive headers. Fix: client-side ping every 30s, exponential reconnect on close. Affected the live P&L panel on iPad specifically.",
    savedBy: "Frontend Agent",
    createdAt: "2026-04-16T12:00:00Z",
    tags: ["safari", "websocket", "dashboard"],
    pipelineRef: { id: "pl-dashboard", label: "Dashboard — live P&L" },
    issueRef: { code: "LT-251", title: "iPad: P&L freezes after ~1min" },
    referencedCount: 8,
    lastAccessedAt: "2026-04-18T09:12:00Z",
  },
  {
    id: "m-3",
    title: "Clerk → NextAuth migration aborted",
    type: "decision",
    content:
      "2 security findings on JWT handling: (1) refresh tokens persisted in localStorage, (2) no rotation on privilege change. Revert to Clerk until Security Agent approves new design. Salvador has veto until re-review.",
    savedBy: "Salvador",
    createdAt: "2026-04-15T16:00:00Z",
    tags: ["auth", "security", "rollback"],
    pipelineRef: { id: "pl-auth", label: "Auth: Clerk → NextAuth" },
    referencedCount: 21,
    lastAccessedAt: "2026-04-18T17:45:00Z",
  },
  {
    id: "m-4",
    title: "Postgres options-greek cache: materialized view, refresh every 15m",
    type: "architecture",
    content:
      "Pre-compute delta/gamma/vega/theta in a materialized view keyed by (symbol, expiry, strike). Refresh on cron every 15min during market hours, full recompute nightly. Avoids hitting the options vendor on every P&L tick.",
    savedBy: "Backend Agent",
    createdAt: "2026-04-14T11:30:00Z",
    tags: ["postgres", "options", "performance"],
    pipelineRef: { id: "pl-dashboard", label: "Dashboard — live P&L" },
    referencedCount: 6,
    lastAccessedAt: "2026-04-17T14:00:00Z",
  },
  {
    id: "m-5",
    title: "Playwright flake: ResizeObserver loop on chart mount",
    type: "bug",
    content:
      "E2E failed intermittently on Firefox when mounting the P&L chart. Root cause: recharts triggers ResizeObserver during measurement. Wrapped the mount in a raf + added `waitForFunction('window.__chartReady')` hook.",
    savedBy: "QA Agent",
    createdAt: "2026-04-13T18:00:00Z",
    tags: ["playwright", "flake", "chart"],
    referencedCount: 4,
    lastAccessedAt: "2026-04-16T10:20:00Z",
  },
  {
    id: "m-6",
    title: "Daniel's voice: never use 'we' in external copy",
    type: "learning",
    content:
      "Rejected 3 marketing drafts because they used 'we'. Operator tone = 'Helm' or 'you'. Salvador confirmed — this is a hard rule, not a preference. Updated brand guide section 5.",
    savedBy: "Marketing Agent",
    createdAt: "2026-04-12T20:00:00Z",
    tags: ["brand", "copy", "voice"],
    referencedCount: 11,
    lastAccessedAt: "2026-04-18T08:30:00Z",
  },
  {
    id: "m-7",
    title: "Bilingual chat: switch happens on user lang, not agent",
    type: "decision",
    content:
      "Concierge agent defaulted to English even when Daniel typed in Spanish. Fix: detect per-message language via first-token heuristic, mirror it in response. ES/EN switch natural — no forced translation.",
    savedBy: "CEO Agent",
    createdAt: "2026-04-11T14:00:00Z",
    tags: ["bilingual", "es-en", "ux"],
    referencedCount: 9,
    lastAccessedAt: "2026-04-17T21:15:00Z",
  },
  {
    id: "m-8",
    title: "Vercel preview URLs must be password-protected",
    type: "learning",
    content:
      "Security Agent flagged that anon preview links leaked staging data to crawlers. Now: every preview deploy gated by Vercel password protection, rotated weekly. DevOps owns the rotation.",
    savedBy: "Security Agent",
    createdAt: "2026-04-10T09:00:00Z",
    tags: ["vercel", "security", "staging"],
    referencedCount: 5,
    lastAccessedAt: "2026-04-15T16:00:00Z",
  },
  {
    id: "m-9",
    title: "React 19 Actions: don't mix with Zustand in same component",
    type: "architecture",
    content:
      "Tried to combine useActionState with Zustand store updates — caused double renders and stale closure bugs. Rule: Actions for server-boundary forms, Zustand for client cache, never both in the same tree.",
    savedBy: "Frontend Agent",
    createdAt: "2026-04-09T13:00:00Z",
    tags: ["react-19", "actions", "zustand"],
    referencedCount: 7,
    lastAccessedAt: "2026-04-16T11:45:00Z",
  },
  {
    id: "m-10",
    title: "PR handoff notes: required format locked in",
    type: "decision",
    content:
      "Every phase handoff must include: (1) what was done, (2) what's next, (3) open questions, (4) memories created this phase. QA rejects handoffs missing any of the four. Enforced in PR template.",
    savedBy: "QA Agent",
    createdAt: "2026-04-08T17:00:00Z",
    tags: ["sdd", "handoff", "process"],
    referencedCount: 18,
    lastAccessedAt: "2026-04-18T19:00:00Z",
  },
  {
    id: "m-11",
    title: "Options vendor rate limit: 300 req/min, use batching",
    type: "learning",
    content:
      "Hit vendor rate limit during backtest. They only allow 300 symbols/min. Backend agent now batches option-chain fetches into groups of 50 with 10s spacing. Postmortem saved to Engram.",
    savedBy: "Backend Agent",
    createdAt: "2026-04-07T10:00:00Z",
    tags: ["api", "rate-limit", "options"],
    referencedCount: 3,
    lastAccessedAt: "2026-04-14T12:00:00Z",
  },
  {
    id: "m-12",
    title: "Modified Sharpe formula — exact coefficients",
    type: "architecture",
    content:
      "Final formula: (mean_excess_return / stddev) * (1 - 0.3 * max_drawdown_ratio). The 0.3 drawdown penalty came from fitting to Salvador's 2022-2024 live track record. Don't tweak without re-benchmarking.",
    savedBy: "CEO Agent",
    createdAt: "2026-04-06T15:30:00Z",
    tags: ["profiler", "formula", "risk"],
    pipelineRef: { id: "pl-profiler", label: "Bryan AI — Profiler v3" },
    referencedCount: 22,
    lastAccessedAt: "2026-04-18T22:30:00Z",
  },
];

// ───── Skills (Knowledge) ─────
const legacySkills: Skill[] = [
  {
    id: "sk-react-19",
    name: "react-19-patterns",
    category: "frontend",
    description: "Actions, useActionState, useOptimistic, server-component boundaries.",
    usedByAgentIds: ["lt-fe", "lt-qa"],
    lastUpdatedAt: "2026-04-16T10:00:00Z",
    lastUpdatedBy: "Daniel",
    invocationsThisWeek: 47,
  },
  {
    id: "sk-nextjs-15",
    name: "nextjs-15-app-router",
    category: "frontend",
    description: "App Router conventions, parallel routes, intercepting routes, streaming.",
    usedByAgentIds: ["lt-fe", "lt-be"],
    lastUpdatedAt: "2026-04-15T09:00:00Z",
    lastUpdatedBy: "Daniel",
    invocationsThisWeek: 38,
  },
  {
    id: "sk-tailwind-4",
    name: "tailwind-4-tokens",
    category: "frontend",
    description: "@theme tokens, custom colors, OKLCH migration, v4 utility classes.",
    usedByAgentIds: ["lt-fe"],
    lastUpdatedAt: "2026-04-14T14:00:00Z",
    lastUpdatedBy: "Daniel",
    invocationsThisWeek: 22,
  },
  {
    id: "sk-typescript-strict",
    name: "typescript-strict",
    category: "frontend",
    description: "strict: true, noUncheckedIndexedAccess, satisfies, const-assertions.",
    usedByAgentIds: ["lt-fe", "lt-be", "lt-qa"],
    lastUpdatedAt: "2026-04-10T11:00:00Z",
    lastUpdatedBy: "Backend Agent",
    invocationsThisWeek: 31,
  },
  {
    id: "sk-playwright",
    name: "playwright-e2e",
    category: "frontend",
    description: "Multi-browser, trace viewer, network stubbing, visual regression.",
    usedByAgentIds: ["lt-qa"],
    lastUpdatedAt: "2026-04-12T16:00:00Z",
    lastUpdatedBy: "QA Agent",
    invocationsThisWeek: 15,
  },
  {
    id: "sk-postgres",
    name: "postgres-schemas",
    category: "backend",
    description: "Materialized views, partitioning, row-level security, explain analyze.",
    usedByAgentIds: ["lt-be"],
    lastUpdatedAt: "2026-04-14T11:00:00Z",
    lastUpdatedBy: "Backend Agent",
    invocationsThisWeek: 19,
  },
  {
    id: "sk-oauth",
    name: "oauth-flows",
    category: "security",
    description: "PKCE, refresh-token rotation, scopes, token binding.",
    usedByAgentIds: ["lt-be", "lt-sec"],
    lastUpdatedAt: "2026-04-15T10:00:00Z",
    lastUpdatedBy: "Security Agent",
    invocationsThisWeek: 8,
  },
  {
    id: "sk-websocket",
    name: "websocket-scaling",
    category: "backend",
    description: "Sticky sessions, Redis pub/sub, keepalive, graceful reconnect.",
    usedByAgentIds: ["lt-be", "lt-fe"],
    lastUpdatedAt: "2026-04-16T08:00:00Z",
    lastUpdatedBy: "Backend Agent",
    invocationsThisWeek: 12,
  },
  {
    id: "sk-kelly",
    name: "kelly-criterion-risk-scoring",
    category: "domain",
    description: "Fractional Kelly, drawdown-penalized variants, portfolio allocation sizing.",
    usedByAgentIds: ["lt-ceo", "lt-be"],
    lastUpdatedAt: "2026-04-17T14:00:00Z",
    lastUpdatedBy: "CEO Agent",
    invocationsThisWeek: 6,
  },
  {
    id: "sk-greeks",
    name: "options-greek-calculations",
    category: "domain",
    description: "Delta, gamma, vega, theta, rho — Black-Scholes and binomial models.",
    usedByAgentIds: ["lt-be", "lt-ceo"],
    lastUpdatedAt: "2026-04-14T11:30:00Z",
    lastUpdatedBy: "Backend Agent",
    invocationsThisWeek: 4,
  },
  {
    id: "sk-sharpe",
    name: "modified-sharpe-ratio",
    category: "domain",
    description: "Drawdown-penalized Sharpe, rolling windows, regime-aware coefficients.",
    usedByAgentIds: ["lt-ceo"],
    lastUpdatedAt: "2026-04-17T15:00:00Z",
    lastUpdatedBy: "CEO Agent",
    invocationsThisWeek: 9,
  },
  {
    id: "sk-secrets",
    name: "secrets-hygiene",
    category: "security",
    description: "No secrets in repo, rotated weekly, per-env vaults, audit on every PR.",
    usedByAgentIds: ["lt-sec", "lt-ops"],
    lastUpdatedAt: "2026-04-10T09:00:00Z",
    lastUpdatedBy: "Security Agent",
    invocationsThisWeek: 17,
  },
  {
    id: "sk-pr-review",
    name: "pr-review-checklist",
    category: "ops",
    description: "Tests pass, security scan clean, brand adherence, handoff notes complete.",
    usedByAgentIds: ["lt-qa", "lt-sec", "lt-ops"],
    lastUpdatedAt: "2026-04-11T09:00:00Z",
    lastUpdatedBy: "QA Agent",
    invocationsThisWeek: 28,
  },
  {
    id: "sk-commits",
    name: "commit-message-conventions",
    category: "ops",
    description: "Conventional commits, scope prefixes, body explains why not what.",
    usedByAgentIds: ["lt-fe", "lt-be", "lt-ops"],
    lastUpdatedAt: "2026-04-08T14:00:00Z",
    lastUpdatedBy: "DevOps Agent",
    invocationsThisWeek: 52,
  },
  {
    id: "sk-brand-voice",
    name: "daniel-brand-voice-es-en",
    category: "marketing",
    description: "Operator tone, em-dashes for asides, bilingual aware, never 'we'.",
    usedByAgentIds: ["lt-ceo", "lt-seo"],
    lastUpdatedAt: "2026-04-12T20:00:00Z",
    lastUpdatedBy: "Daniel",
    invocationsThisWeek: 14,
  },
];

// ───── Brand Guide (Knowledge) ─────
const legacyBrandGuide: BrandGuide = {
  updatedAt: "2026-04-17T10:00:00Z",
  updatedBy: "Daniel",
  referencedByAgentIds: ["lt-ceo", "lt-fe", "lt-seo"],
  voice: [
    {
      title: "Direct, no corporate fluff",
      detail: "Say the thing. No 'leverage synergies' — just the verb that matches the action.",
    },
    {
      title: "Bilingual aware (ES/EN)",
      detail: "Switch natural. Spanish for internal ops, English for product copy and external.",
    },
    {
      title: "Operator-to-operator",
      detail: "Never expert-to-beginner. The reader already runs their own company.",
    },
    {
      title: "Respect attention",
      detail: "Lead with the outcome. If the first sentence could be deleted, delete it.",
    },
    {
      title: "Show numbers when they matter",
      detail: "'47 issues closed' beats 'many issues closed'. Concrete > vague.",
    },
  ],
  colors: [
    { label: "Deep", hex: "#0c0a08", token: "bg-deep" },
    { label: "Page", hex: "#110f0c", token: "bg-page" },
    { label: "Surface", hex: "#1a1713", token: "bg-surface" },
    { label: "Elevated", hex: "#2a241d", token: "bg-elevated" },
    { label: "Brass", hex: "#c89b5e", token: "brass" },
    { label: "Brass bright", hex: "#e5b87a", token: "brass-bright" },
    { label: "Brass muted", hex: "#8a6d43", token: "brass-muted" },
    { label: "Teal", hex: "#4a7a82", token: "teal" },
    { label: "Success", hex: "#7ba05b", token: "success" },
    { label: "Warning", hex: "#d4a23e", token: "warning" },
    { label: "Danger", hex: "#c26b55", token: "danger" },
  ],
  typography: [
    {
      label: "Display serif",
      font: "serif",
      sample: "Pipelines in flight.",
      meta: "Fraunces · weight 300 · tracking -0.025em",
    },
    {
      label: "Display italic",
      font: "serif",
      sample: "What your agents know.",
      meta: "Fraunces italic · weight 400 · tracking -0.02em",
    },
    {
      label: "UI body",
      font: "sans",
      sample: "Direct, no corporate fluff. Say the thing.",
      meta: "Inter Tight · 14px · tracking -0.01em",
    },
    {
      label: "Mono meta",
      font: "mono",
      sample: "STARTED 2d AGO · PR #247 · DANIEL",
      meta: "JetBrains Mono · 11px · tracking 0.02em",
    },
    {
      label: "Mono label",
      font: "mono",
      sample: "PHASE TIMELINE",
      meta: "JetBrains Mono · 10px · tracking 0.15em · uppercase",
    },
  ],
  icons: [
    { name: "Home", role: "Command center" },
    { name: "GitBranch", role: "Activity / branches" },
    { name: "Layers", role: "Knowledge" },
    { name: "MessageSquare", role: "Helm Chat" },
    { name: "BarChart3", role: "Reports" },
    { name: "ChevronRight", role: "Breadcrumbs / drill-in" },
    { name: "CheckCircle2", role: "Done / success" },
    { name: "AlertTriangle", role: "Attention / blocked" },
    { name: "Clock", role: "Pending / queued" },
    { name: "Github", role: "PR / repo" },
  ],
  writing: [
    {
      rule: "Use em-dashes for asides, not commas",
      example: "The profiler — rebuilt last month — now uses modified Sharpe.",
    },
    {
      rule: "Avoid 'we' — use 'Helm' or 'you'",
      example: "Helm watches every pipeline. You approve what ships.",
    },
    {
      rule: "Numbers: cardinal under 10, digits over",
      example: "Three agents are idle. 47 issues closed this month.",
    },
    {
      rule: "Bilingual: ES for internal ops, EN for product copy",
      example: "Internal: 'Dale, mandá el handoff'. Product: 'Ship the handoff.'",
    },
    {
      rule: "No exclamation marks, ever",
      example: "'Pipeline done.' not 'Pipeline done!'",
    },
  ],
};

// ───── SOPs (Knowledge) ─────
const legacySOPs: SOP[] = [
  {
    id: "sop-deploy",
    title: "Deploy Process",
    description: "From PR open to production, the six-gate path.",
    linkedAgentIds: ["lt-be", "lt-qa", "lt-sec", "lt-ops"],
    triggeredThisMonth: 12,
    lastTriggeredAt: "2026-04-18T16:00:00Z",
    steps: [
      { title: "Code review", detail: "Backend or Frontend agent reviews the diff, checks patterns." },
      { title: "QA sign-off", detail: "Playwright e2e green on Chrome, Firefox, Safari." },
      { title: "Security scan", detail: "Security agent runs dep audit + secrets scan, must be clean." },
      { title: "Staging deploy", detail: "Auto-deploy to preview URL, password-protected." },
      { title: "Smoke test", detail: "3 critical paths exercised manually or by smoke script." },
      { title: "Prod rollout", detail: "Canary 10% → full. Rollback ready, DevOps on call." },
    ],
  },
  {
    id: "sop-pr-review",
    title: "PR Review Checklist",
    description: "Every PR, every time. No exceptions — ever.",
    linkedAgentIds: ["lt-qa", "lt-sec"],
    triggeredThisMonth: 28,
    lastTriggeredAt: "2026-04-18T21:00:00Z",
    steps: [
      { title: "Tests pass", detail: "pnpm typecheck && pnpm build && pnpm test:e2e all green." },
      { title: "Security scan clean", detail: "No new secrets, no new vulnerable deps." },
      { title: "Brand guide adherence", detail: "Copy matches voice, colors match tokens." },
      { title: "Handoff notes complete", detail: "Four sections: done, next, questions, memories." },
      { title: "Linked memories created", detail: "Every non-obvious decision gets an Engram entry." },
    ],
  },
  {
    id: "sop-agent-onboarding",
    title: "Agent Onboarding",
    description: "Spinning up a new agent inside an existing company.",
    linkedAgentIds: ["lt-ceo"],
    triggeredThisMonth: 2,
    lastTriggeredAt: "2026-04-11T09:00:00Z",
    steps: [
      { title: "Load persona from Knowledge", detail: "Pull role definition and skill list." },
      { title: "Load relevant skills", detail: "Category-matched skills auto-attached." },
      { title: "Seed memories from past similar tasks", detail: "Top 10 memories by tag relevance." },
      { title: "Intro call with CEO agent", detail: "Two-turn handshake confirming scope and budget." },
    ],
  },
  {
    id: "sop-incident",
    title: "Incident Response",
    description: "Prod broke. Here's the five-step lane.",
    linkedAgentIds: ["lt-ops", "lt-be", "lt-sec"],
    triggeredThisMonth: 1,
    lastTriggeredAt: "2026-04-13T02:30:00Z",
    steps: [
      { title: "Detect", detail: "Alert fires or user reports. Page on-call agent + Daniel." },
      { title: "Isolate", detail: "Identify blast radius. Flip feature flag if possible." },
      { title: "Rollback", detail: "Revert to last known good deploy. Confirm recovery." },
      { title: "Investigate", detail: "Root cause. Repro locally. Write fix on branch." },
      { title: "Postmortem", detail: "Blameless. Memory saved to Engram on resolution." },
    ],
  },
  {
    id: "sop-quality",
    title: "Code Quality Gates",
    description: "Four machines that must say yes before merge.",
    linkedAgentIds: ["lt-qa", "lt-fe", "lt-be"],
    triggeredThisMonth: 34,
    lastTriggeredAt: "2026-04-18T20:10:00Z",
    steps: [
      { title: "pnpm typecheck", detail: "Zero errors. No 'any' escapes unless justified in comment." },
      { title: "pnpm build", detail: "Next.js build green, no warnings flagged as errors." },
      { title: "playwright e2e", detail: "Full suite on Chrome + Firefox + Safari." },
      { title: "No console.errors", detail: "Dev-server run, exercise golden path, check console." },
    ],
  },
  {
    id: "sop-bilingual-support",
    title: "Bilingual Customer Support",
    description: "Flagler BNB playbook, applicable to any customer-facing support.",
    linkedAgentIds: ["lt-seo"],
    triggeredThisMonth: 6,
    lastTriggeredAt: "2026-04-17T18:00:00Z",
    steps: [
      { title: "Respond in <90s", detail: "First-touch latency is the #1 driver of NPS." },
      { title: "Tone: warm but precise", detail: "No fake empathy. Just acknowledge + solve." },
      { title: "Match guest language", detail: "ES/EN detected per message. Mirror, don't translate." },
      { title: "Escalate to human if >2 turns", detail: "Loop Salvador or Daniel on the third reply." },
    ],
  },
];

// ───── Companies ─────
export const seedCompanies: Company[] = [
  {
    id: "legacy-traders",
    name: "Legacy Traders",
    slug: "legacy-traders",
    colorHex: "#c26b55",
    industry: "Trading · SaaS",
    status: "active",
    monthlyBudget: 1200,
    monthlySpendMtd: 684,
    openTickets: 12,
    closedTickets: 47,
    activePipelines: 3,
    agents: [
      mkCEO("lt-ceo"),
      mkFrontend("lt-fe"),
      mkBackend("lt-be"),
      mkDevOps("lt-ops"),
      mkQA("lt-qa"),
      mkSecurity("lt-sec"),
      mkSEO("lt-seo"),
    ],
    humans: [salvador, daniel],
    pipelines: [legacyProfilerPipeline, legacyDashboardPipeline, legacyAuthPipeline],
    issues: legacyIssues,
    memories: legacyMemories,
    streamItems: legacyStreamItems,
    skills: legacySkills,
    brandGuide: legacyBrandGuide,
    sops: legacySOPs,
    todaySpend: 38.12,
    yesterdaySpend: 48.90,
    daysLeftInMonth: 12,
    stagePills: ["Trading · SaaS", "Production", "+Salvador"],
    keyMetric: { label: "Velocity", value: "↑ 2.3×", sub: "vs solo" },
  },
  {
    id: "multi-topup",
    name: "Multi Topup",
    slug: "multi-topup",
    colorHex: "#4a7a82",
    industry: "SaaS · Custom Software",
    status: "active",
    monthlyBudget: 800,
    monthlySpendMtd: 312,
    openTickets: 4,
    closedTickets: 23,
    activePipelines: 1,
    agents: [mkCEO("mt-ceo"), mkFrontend("mt-fe"), mkBackend("mt-be"), mkQA("mt-qa")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    streamItems: emptyStream("mt"),
    todaySpend: 14.20,
    yesterdaySpend: 22.80,
    daysLeftInMonth: 12,
    stagePills: ["SaaS", "Active"],
  },
  {
    id: "mh-home-solutions",
    name: "MH Home Solutions",
    slug: "mh-home-solutions",
    colorHex: "#7ba05b",
    industry: "Home Services · Local",
    status: "attention",
    monthlyBudget: 400,
    monthlySpendMtd: 142,
    openTickets: 7,
    closedTickets: 18,
    activePipelines: 1,
    agents: [mkCEO("mh-ceo"), mkMarketing("mh-mkt"), mkFrontend("mh-fe"), mkSEO("mh-seo"), mkQA("mh-qa")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    streamItems: emptyStream("mh"),
    todaySpend: 6.40,
    yesterdaySpend: 9.10,
    daysLeftInMonth: 12,
    stagePills: ["Local services", "Growth"],
    keyMetric: { label: "Leads / week", value: "23", sub: "qualified" },
  },
  {
    id: "flagler-bnb",
    name: "Flagler Beach BNB",
    slug: "flagler-bnb",
    colorHex: "#d4a23e",
    industry: "Hospitality · STR",
    status: "active",
    monthlyBudget: 200,
    monthlySpendMtd: 48,
    openTickets: 3,
    closedTickets: 31,
    activePipelines: 0,
    agents: [mkCEO("fb-ceo"), mkConcierge("fb-g", "Guest Concierge"), mkConcierge("fb-h", "Host Assistant")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    streamItems: emptyStream("fb"),
    todaySpend: 1.80,
    yesterdaySpend: 2.40,
    daysLeftInMonth: 12,
    stagePills: ["Hospitality", "Ops"],
    keyMetric: { label: "Occupancy", value: "87%", sub: "next 60d" },
  },
  {
    id: "charge2go",
    name: "Charge2Go",
    slug: "charge2go",
    colorHex: "#c89b5e",
    industry: "EV Infrastructure",
    status: "active",
    monthlyBudget: 600,
    monthlySpendMtd: 268,
    openTickets: 5,
    closedTickets: 14,
    activePipelines: 2,
    agents: [mkCEO("c2g-ceo"), mkFrontend("c2g-fe"), mkBackend("c2g-be"), mkDevOps("c2g-ops"), mkSEO("c2g-seo")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    streamItems: emptyStream("c2g"),
    todaySpend: 12.10,
    yesterdaySpend: 18.50,
    daysLeftInMonth: 12,
    stagePills: ["Infra", "Active"],
  },
  {
    id: "minari",
    name: "Minari Solutions",
    slug: "minari",
    colorHex: "#8a6d43",
    industry: "Custom Software",
    status: "active",
    monthlyBudget: 300,
    monthlySpendMtd: 87,
    openTickets: 2,
    closedTickets: 8,
    activePipelines: 1,
    agents: [mkCEO("mn-ceo"), mkBackend("mn-be")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    streamItems: emptyStream("mn"),
    todaySpend: 3.20,
    yesterdaySpend: 4.60,
    daysLeftInMonth: 12,
    stagePills: ["Custom", "Active"],
  },
];

// ───── Approvals ─────
export const seedApprovals: Approval[] = [
  {
    id: "app-1",
    companyId: "legacy-traders",
    companyName: "Legacy Traders",
    type: "hire",
    title: "Hire: Backend Engineer",
    description: "CEO agent requests backend hire for Bryan AI profiler refactor. GPT-5.4 recommended.",
    requesterAgentLabel: "CEO Agent",
    tag: "$400/mo cap",
    createdAt: "2026-04-18T09:15:00Z",
  },
  {
    id: "app-2",
    companyId: "legacy-traders",
    companyName: "Legacy Traders",
    type: "deploy",
    title: "Deploy to production",
    description: "Checkout v2 passed all QA gates. Playwright E2E ✓ · Security scan ✓",
    requesterAgentLabel: "Backend Agent",
    tag: "Legacy Traders",
    createdAt: "2026-04-18T09:40:00Z",
    impact: {
      "Users affected": "1,247 active",
      "QA pass rate": "100%",
      "Rollback ready": "Yes · 15s",
      "Security scan": "Clean",
    },
  },
  {
    id: "app-3",
    companyId: "mh-home-solutions",
    companyName: "MH Home Solutions",
    type: "budget",
    title: "Budget increase request",
    description: "Marketing agent wants +$150/mo for paid lead acquisition experiments.",
    requesterAgentLabel: "Marketing Agent",
    tag: "+$150/mo",
    createdAt: "2026-04-18T08:20:00Z",
  },
  {
    id: "app-4",
    companyId: "charge2go",
    companyName: "Charge2Go",
    type: "spec-review",
    title: "Spec review: EV Station Finder PRD",
    description: "New sub-product PRD ready for your sign-off before pipeline kicks off.",
    requesterAgentLabel: "CEO Agent",
    tag: "Pre-pipeline",
    createdAt: "2026-04-18T10:05:00Z",
  },
];

// ───── Activity stream ─────
export const seedActivityStream: ActivityEntry[] = [
  {
    id: "a-1",
    timestamp: "2026-04-18T10:41:00Z",
    level: "success",
    agentLabel: "Frontend Dev · Sonnet",
    companyName: "Legacy Traders",
    text: "shipped checkout flow v2 to staging",
    meta: "QA verification passed · 1m 24s · $0.42",
  },
  {
    id: "a-2",
    timestamp: "2026-04-18T10:29:00Z",
    level: "warning",
    agentLabel: "Security Advisor · Opus",
    companyName: "Legacy Traders",
    text: "flagged 2 findings on auth refactor",
    meta: "Awaiting your review · 12m ago",
  },
  {
    id: "a-3",
    timestamp: "2026-04-18T10:07:00Z",
    level: "neutral",
    agentLabel: "Interview Agent",
    companyName: "Charge2Go",
    text: "drafted PRD for EV Station Finder Mobile",
    meta: "Converted to Company · ready for kickoff · 34m ago",
  },
  {
    id: "a-4",
    timestamp: "2026-04-18T09:55:00Z",
    level: "success",
    agentLabel: "Guest Concierge",
    companyName: "Flagler BNB",
    text: "replied to 4 Airbnb inquiries in ES + EN",
    meta: "All under 90s response time · $0.06 total",
  },
];

// ───── Threads (Helm Chat) ─────
export const seedThreads: Thread[] = [
  {
    id: "t-ev-finder",
    title: "EV Station Finder",
    role: "interview",
    messages: [
      {
        id: "m1",
        role: "assistant",
        content:
          "Hola, soy el Interview Agent. Vamos a convertir una idea en una empresa lista para ejecutar. Respondé crudo, como a un socio.\n\n¿Qué estás tratando de construir — y para quién duele tanto este problema que lo pagarían hoy?",
        timestamp: "2026-04-18T11:42:00Z",
      },
      {
        id: "m2",
        role: "user",
        content:
          "Los dueños de Teslas en Florida se frustran cuando viajan a zonas nuevas porque los estimados de las apps no consideran elevación, viento ni clima. La gente termina llegando con 4% de batería o manejando 30 millas fuera de ruta a un charger equivocado. Tengo la data de carga de Charge2Go pero necesito un front para dueños de EV, no para operadores de stations.",
        timestamp: "2026-04-18T11:43:00Z",
        attachments: [
          { id: "att-1", type: "pdf", fileName: "charge2go-research.pdf", sizeLabel: "2.4 MB · 18 pages" },
          { id: "att-2", type: "image", fileName: "whiteboard-sketch.jpg", sizeLabel: "1.1 MB · from iPhone" },
        ],
      },
      {
        id: "m3",
        role: "assistant",
        content:
          "Leí el PDF y el sketch. Entiendo tres cosas: es B2C, datos reales de Charge2Go, y la ventaja competitiva es física (weather + elevation), no mejor UI.\n\nAntes de armarte el PRD, dos cosas que definen el stack:",
        timestamp: "2026-04-18T11:43:30Z",
        suggestionGroups: [
          { label: "Form factor", options: ["🚗 Mobile-first (PWA)", "💻 Landing + web app", "📱 Native app (iOS + Android)"] },
          { label: "Timeline", options: ["⚡ MVP en 2 semanas", "🎯 Producto sólido en 6 semanas", "🏗️ Plataforma completa en 12"] },
        ],
        prdPreview: {
          title: "EV Station Finder",
          description:
            "Mobile-first PWA for EV owners in Florida. Real-time range estimates factoring weather, elevation, and live charger availability from the Charge2Go network.",
          stackPills: ["Next.js 15", "Tailwind", "PWA"],
          parentCompany: "Charge2Go (new sub-product)",
          coreFeatures: "Map · Range calc · Weather API · Live availability",
          agentsToHire: "CEO · Frontend · Backend · QA · SEO",
          confidencePercent: 94,
        },
      },
    ],
    createdAt: "2026-04-18T11:42:00Z",
    updatedAt: "2026-04-18T11:43:30Z",
    totalCost: 0.34,
  },
  {
    id: "t-mh-pricing",
    title: "MH pricing calc",
    role: "strategy",
    messages: [],
    createdAt: "2026-04-17T16:20:00Z",
    updatedAt: "2026-04-17T16:55:00Z",
    totalCost: 0.18,
  },
  {
    id: "t-trading-journal",
    title: "Trading journal v3",
    role: "architect",
    messages: [],
    createdAt: "2026-04-15T09:00:00Z",
    updatedAt: "2026-04-16T14:10:00Z",
    totalCost: 0.52,
  },
  {
    id: "t-dock-pilings",
    title: "Dock pilings Q&A",
    role: "interview",
    messages: [],
    createdAt: "2026-04-13T11:45:00Z",
    updatedAt: "2026-04-13T12:10:00Z",
    totalCost: 0.09,
  },
  {
    id: "t-bryan-roadmap",
    title: "Bryan AI roadmap",
    role: "strategy",
    messages: [],
    createdAt: "2026-04-10T10:15:00Z",
    updatedAt: "2026-04-12T17:40:00Z",
    totalCost: 0.71,
  },
];

// ───── Roles (chat sidebar) ─────
export const seedRoles: AgentRole[] = [
  {
    id: "interview",
    name: "Interview Agent",
    model: "Opus 4.7",
    meta: "bilingual",
    colorHex: "#c89b5e",
  },
  {
    id: "strategy",
    name: "Strategy Advisor",
    model: "Opus 4.7",
    meta: "market · positioning",
    colorHex: "#4a7a82",
  },
  {
    id: "architect",
    name: "Technical Architect",
    model: "Sonnet · GPT-5.4",
    meta: "stack · tradeoffs",
    colorHex: "#7ba05b",
  },
  {
    id: "reviewer",
    name: "QA Reviewer",
    model: "Codex · Playwright",
    meta: "testable · edge cases",
    colorHex: "#d4a23e",
  },
];

// ───── PRD draft progress (right panel) ─────
export const seedPRDDraft: PRDSection[] = [
  { id: "problem", label: "Problem statement", status: "done" },
  { id: "users", label: "Target users", status: "done" },
  { id: "metrics", label: "Success metrics", status: "in-progress" },
  { id: "competitive", label: "Competitive landscape", status: "pending" },
  { id: "tech", label: "Tech requirements", status: "pending" },
];

// ───── Inspiration cards (right panel) ─────
export const seedInspiration: InspirationCard[] = [
  {
    id: "insp-1",
    title: "Mercado Libre logistics",
    subtitle: "Real-time fleet visibility · route optimization at LATAM scale",
    sourceUrl: "envios.mercadolibre.com",
    tag: "Logistics",
  },
  {
    id: "insp-2",
    title: "Tesla Supercharger Map",
    subtitle: "Live availability · queue time · trip planner baseline",
    sourceUrl: "tesla.com/findus",
    tag: "Reference UX",
  },
];

// ───── Interview Agent ghost messages (demo mode) ─────
export const interviewGhostMessages: string[] = [
  "Una pregunta más antes de firmar el PRD: ¿cómo monetizás? ¿suscripción a dueños de EV, revenue share con Charge2Go, o data-as-a-service a fleets?",
  "Pensando en modo negocio: ¿qué pasaría si Tesla lanza la misma feature en 6 semanas? ¿Tu ventaja aguanta o necesitamos pivote?",
  "Te escuché. Antes de cerrar, ¿hay un guardrail no-negociable? ej: no vender ubicación, no push notifications agresivas, no dark patterns.",
];

// ───── EV Station Finder Company seed (built on Convert) ─────
export function buildEVStationFinderCompany(): Company {
  const discoveryPipeline: Pipeline = {
    id: "p-evsf-discovery",
    featureName: "Discovery — Florida EV owner research",
    startedAt: "2026-04-18T12:00:00Z",
    ownerAgentId: "evsf-ceo",
    currentPhaseIndex: 1,
    progressPercent: 18,
    phases: [
      { name: "explore", displayName: "Explore", status: "done", assignedLabel: "CEO", durationLabel: "✓ 4m" },
      { name: "propose", displayName: "Propose", status: "active", assignedLabel: "CEO", durationLabel: "● running" },
      { name: "spec", displayName: "Spec", status: "pending", assignedLabel: "Arch", durationLabel: "queued" },
      { name: "design", displayName: "Design", status: "pending", assignedLabel: "Opus", durationLabel: "—" },
      { name: "implement", displayName: "Implement", status: "pending", assignedLabel: "FE + BE", durationLabel: "—" },
      { name: "verify", displayName: "Verify", status: "pending", assignedLabel: "QA", durationLabel: "—" },
      { name: "archive", displayName: "Archive", status: "pending", assignedLabel: "Docs", durationLabel: "—" },
    ],
  };

  const mvpPipeline: Pipeline = {
    id: "p-evsf-mvp",
    featureName: "MVP — Map + range calc + live availability",
    startedAt: "2026-04-18T12:00:00Z",
    ownerAgentId: "evsf-fe",
    currentPhaseIndex: 0,
    progressPercent: 4,
    phases: [
      { name: "explore", displayName: "Explore", status: "active", assignedLabel: "FE", durationLabel: "● starting" },
      { name: "propose", displayName: "Propose", status: "pending", assignedLabel: "FE", durationLabel: "queued" },
      { name: "spec", displayName: "Spec", status: "pending", assignedLabel: "Arch", durationLabel: "—" },
      { name: "design", displayName: "Design", status: "pending", assignedLabel: "Opus", durationLabel: "—" },
      { name: "implement", displayName: "Implement", status: "pending", assignedLabel: "FE + BE", durationLabel: "—" },
      { name: "verify", displayName: "Verify", status: "pending", assignedLabel: "QA", durationLabel: "—" },
      { name: "archive", displayName: "Archive", status: "pending", assignedLabel: "Docs", durationLabel: "—" },
    ],
  };

  const launchPipeline: Pipeline = {
    id: "p-evsf-launch",
    featureName: "Launch — App store, PWA install, onboarding",
    startedAt: "2026-04-18T12:00:00Z",
    ownerAgentId: "evsf-ceo",
    currentPhaseIndex: 0,
    progressPercent: 0,
    phases: [
      { name: "explore", displayName: "Explore", status: "pending", assignedLabel: "CEO", durationLabel: "scheduled" },
      { name: "propose", displayName: "Propose", status: "pending", assignedLabel: "CEO", durationLabel: "—" },
      { name: "spec", displayName: "Spec", status: "pending", assignedLabel: "Arch", durationLabel: "—" },
      { name: "design", displayName: "Design", status: "pending", assignedLabel: "Opus", durationLabel: "—" },
      { name: "implement", displayName: "Implement", status: "pending", assignedLabel: "FE", durationLabel: "—" },
      { name: "verify", displayName: "Verify", status: "pending", assignedLabel: "QA", durationLabel: "—" },
      { name: "archive", displayName: "Archive", status: "pending", assignedLabel: "Docs", durationLabel: "—" },
    ],
  };

  const issues: Issue[] = [
    {
      id: "evsf-001",
      code: "EVSF-001",
      title: "Research: Florida EV owner pain points",
      subtitle: "Discovery · 10 interviews target · ES + EN",
      description: "Surface top 3 unmet needs for range anxiety on long FL routes.",
      status: "in-progress",
      assigneeLabel: "CEO",
      assigneeColor: "brass",
      pipelineId: "p-evsf-discovery",
      costSoFar: 0.04,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-002",
      code: "EVSF-002",
      title: "Integrate Charge2Go live availability API",
      subtitle: "MVP · backend · auth + rate limits",
      description: "Connect internal Charge2Go feed with per-station availability.",
      status: "queued",
      assigneeLabel: "BE",
      assigneeColor: "teal",
      pipelineId: "p-evsf-mvp",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-003",
      code: "EVSF-003",
      title: "Weather + elevation-aware range estimator",
      subtitle: "Core differentiator · physics model",
      description: "Adjust remaining range using NOAA wind + 10m elevation DEM.",
      status: "queued",
      assigneeLabel: "BE",
      assigneeColor: "teal",
      pipelineId: "p-evsf-mvp",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-004",
      code: "EVSF-004",
      title: "Map view with live charger pins",
      subtitle: "Mapbox · color-coded availability",
      description: "Mobile-first map with clustering + charger detail sheet.",
      status: "queued",
      assigneeLabel: "FE",
      assigneeColor: "teal",
      pipelineId: "p-evsf-mvp",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-005",
      code: "EVSF-005",
      title: "PWA shell + install prompt",
      subtitle: "Launch · offline map cache",
      description: "Service worker + manifest + install UX.",
      status: "queued",
      assigneeLabel: "FE",
      assigneeColor: "teal",
      pipelineId: "p-evsf-launch",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-006",
      code: "EVSF-006",
      title: "Onboarding: select your EV model",
      subtitle: "Pre-populate battery curve per model",
      description: "Model picker → battery profile → personalized range UX.",
      status: "queued",
      assigneeLabel: "FE",
      assigneeColor: "teal",
      pipelineId: "p-evsf-launch",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-007",
      code: "EVSF-007",
      title: "E2E test harness: Miami → Orlando trip",
      subtitle: "Playwright · mock GPS · edge-case coverage",
      description: "Automated trip sim with dead-battery and reroute paths.",
      status: "queued",
      assigneeLabel: "QA",
      assigneeColor: "danger",
      pipelineId: "p-evsf-mvp",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
    {
      id: "evsf-008",
      code: "EVSF-008",
      title: "SEO landing: florida-ev-charger-map",
      subtitle: "ES + EN · structured data · long-tail",
      description: "Static SEO surface to drive acquisition.",
      status: "queued",
      assigneeLabel: "SEO",
      assigneeColor: "teal",
      pipelineId: "p-evsf-launch",
      costSoFar: 0,
      createdAt: "2026-04-18T12:00:00Z",
    },
  ];

  const streamItems: StreamItem[] = [
    {
      id: "evsf-s-1",
      agentLabel: "CEO · OPUS",
      action: "provisioning",
      timeLabel: "NOW",
      body: "Context graph seeded from <code>t-ev-finder</code> · 47 memories linked from Charge2Go",
    },
    {
      id: "evsf-s-2",
      agentLabel: "FE · SONNET",
      action: "scaffolding",
      timeLabel: "2s",
      body: "Generating <code>app/(map)</code> route group + PWA manifest",
    },
    {
      id: "evsf-s-3",
      agentLabel: "BE · GPT-5.4",
      action: "planning",
      timeLabel: "8s",
      body: "Drafting physics-aware range calc spec · weather API shortlist",
    },
  ];

  return {
    id: "ev-station-finder",
    name: "EV Station Finder",
    slug: "ev-station-finder",
    colorHex: "#c89b5e",
    industry: "EV · Mobile",
    status: "active",
    monthlyBudget: 500,
    monthlySpendMtd: 0,
    openTickets: issues.filter((i) => i.status !== "done").length,
    closedTickets: 0,
    activePipelines: 3,
    agents: [
      mkCEO("evsf-ceo"),
      mkFrontend("evsf-fe"),
      mkBackend("evsf-be"),
      mkQA("evsf-qa"),
    ],
    humans: [daniel],
    pipelines: [discoveryPipeline, mvpPipeline, launchPipeline],
    issues,
    memories: [],
    streamItems,
    todaySpend: 0.04,
    yesterdaySpend: 0,
    daysLeftInMonth: 12,
    stagePills: ["EV · Mobile", "Just created", "Charge2Go sub-product"],
    keyMetric: { label: "PRD confidence", value: "94%", sub: "auto-generated" },
  };
}
