import type {
  Company,
  Approval,
  ActivityEntry,
  Thread,
  Agent,
  Human,
  Pipeline,
  Issue,
  Memory,
} from "./types";

// ───── Agents (reusable templates) ─────
const mkCEO = (id: string): Agent => ({
  id,
  role: "CEO · Strategist",
  shortRole: "CEO",
  roleColor: "brass",
  name: "CEO Agent",
  model: "Opus 4.7",
  provider: "anthropic",
  status: "working",
  todayCost: 12.4,
  lifetimeCost: 482.1,
  skills: ["strategy", "delegation", "bilingual-es-en", "daniel-taste-pack"],
  persona: "Senior founder-operator. Challenges assumptions. Bilingual ES/EN.",
});

const mkFrontend = (id: string): Agent => ({
  id,
  role: "Frontend Engineer",
  shortRole: "FE",
  roleColor: "teal",
  name: "Frontend Agent",
  model: "Claude Code · Sonnet",
  provider: "anthropic",
  status: "working",
  todayCost: 8.1,
  lifetimeCost: 214.4,
  skills: ["react-19", "nextjs-15", "tailwind-4", "responsive"],
  persona: "Senior frontend dev. Ships responsive, accessible components.",
});

const mkBackend = (id: string): Agent => ({
  id,
  role: "Backend Engineer",
  shortRole: "BE",
  roleColor: "teal",
  name: "Backend Agent",
  model: "Codex · GPT-5.4",
  provider: "openai",
  status: "idle",
  todayCost: 5.2,
  lifetimeCost: 198.6,
  skills: ["node", "postgres", "api-design", "auth-patterns"],
  persona: "Backend architect. Type-safe by default. Async-first.",
});

const mkDevOps = (id: string): Agent => ({
  id,
  role: "DevOps",
  shortRole: "OPS",
  roleColor: "success",
  name: "DevOps Agent",
  model: "Sonnet · GitHub App",
  provider: "anthropic",
  status: "idle",
  todayCost: 1.8,
  lifetimeCost: 48.2,
  skills: ["ci-cd", "vercel", "cloudflare", "monitoring"],
  persona: "Infra steward. No credentials in code, ever.",
});

const mkQA = (id: string): Agent => ({
  id,
  role: "QA Reviewer",
  shortRole: "QA",
  roleColor: "danger",
  name: "QA Agent",
  model: "Codex · Playwright",
  provider: "openai",
  status: "working",
  todayCost: 4.4,
  lifetimeCost: 132.1,
  skills: ["playwright", "e2e-testing", "accessibility"],
  persona: "Test every button. Report every break.",
});

const mkSecurity = (id: string): Agent => ({
  id,
  role: "Security Advisor",
  shortRole: "SEC",
  roleColor: "warning",
  name: "Security Agent",
  model: "Opus · read-only",
  provider: "anthropic",
  status: "idle",
  todayCost: 0.8,
  lifetimeCost: 22.4,
  skills: ["threat-modeling", "owasp", "secrets-hygiene"],
  persona: "Read-only. Flags risk before it ships.",
});

const mkSEO = (id: string): Agent => ({
  id,
  role: "SEO Specialist",
  shortRole: "SEO",
  roleColor: "teal",
  name: "SEO Agent",
  model: "Sonnet",
  provider: "anthropic",
  status: "idle",
  todayCost: 0.4,
  lifetimeCost: 12.8,
  skills: ["technical-seo", "content-strategy", "keyword-research"],
  persona: "Audit every page. Recommend, don't rewrite.",
});

const mkMarketing = (id: string): Agent => ({
  id,
  role: "Marketing Agent",
  shortRole: "M",
  roleColor: "success",
  name: "Marketing Agent",
  model: "Sonnet",
  provider: "anthropic",
  status: "working",
  todayCost: 3.1,
  lifetimeCost: 86.4,
  skills: ["copywriting-es-en", "brand-voice", "local-seo"],
  persona: "Writes in Daniel's brand voice. Bilingual.",
});

const mkConcierge = (id: string, name: string): Agent => ({
  id,
  role: name,
  shortRole: name === "Guest Concierge" ? "G" : "H",
  roleColor: "success",
  name,
  model: "Sonnet",
  provider: "anthropic",
  status: "working",
  todayCost: 0.6,
  lifetimeCost: 18.4,
  skills: ["hospitality", "bilingual-es-en", "airbnb-messaging"],
  persona: "Warm, professional, replies in <90s.",
});

// ───── Humans ─────
const salvador: Human = {
  id: "salvador",
  name: "Salvador",
  role: "Full-stack developer",
  status: "online",
  initials: "S",
};

const daniel: Human = {
  id: "daniel",
  name: "Daniel (you)",
  role: "Chairman",
  status: "online",
  initials: "DT",
};

// ───── Pipelines ─────
const legacyProfilerPipeline: Pipeline = {
  id: "p-lt-profiler-v3",
  featureName: "Bryan AI — Profiler v3 (trader risk profiles)",
  startedAt: "2026-04-16T09:00:00Z",
  ownerAgentId: "lt-ceo",
  prNumber: 247,
  currentPhaseIndex: 3,
  progressPercent: 55,
  phases: [
    { name: "explore", displayName: "Explore", status: "done", assignedLabel: "CEO", durationLabel: "✓ done" },
    { name: "propose", displayName: "Propose", status: "done", assignedLabel: "CEO", durationLabel: "✓ 12m 41s" },
    { name: "spec", displayName: "Spec", status: "done", assignedLabel: "Arch", durationLabel: "✓ Salvador ✓" },
    { name: "design", displayName: "Design", status: "active", assignedLabel: "Opus", durationLabel: "● running 3m" },
    { name: "implement", displayName: "Implement", status: "pending", assignedLabel: "FE + BE", durationLabel: "queued" },
    { name: "verify", displayName: "Verify", status: "pending", assignedLabel: "QA", durationLabel: "Playwright" },
    { name: "archive", displayName: "Archive", status: "pending", assignedLabel: "Docs", durationLabel: "—" },
  ],
};

// ───── Issues ─────
const legacyIssues: Issue[] = [
  {
    id: "lt-247",
    code: "LT-247",
    title: "Bryan AI profiler v3 — risk score algorithm",
    subtitle: "Pipeline active · design phase · blocks 3 downstream",
    description: "Compute risk score from historical P&L + volatility metrics.",
    status: "in-progress",
    assigneeLabel: "A",
    assigneeColor: "brass",
    pipelineId: "p-lt-profiler-v3",
    costSoFar: 42.10,
    createdAt: "2026-04-16T09:00:00Z",
  },
  {
    id: "lt-251",
    code: "LT-251",
    title: "Dashboard — real-time P&L streaming",
    subtitle: "WebSocket refactor · needs your review on approach",
    description: "Move from polling to WebSocket for live P&L updates.",
    status: "review",
    assigneeLabel: "FE",
    assigneeColor: "teal",
    costSoFar: 18.44,
    createdAt: "2026-04-17T14:20:00Z",
  },
  {
    id: "lt-248",
    code: "LT-248",
    title: "Auth: migrate from Clerk to NextAuth",
    subtitle: "Security flagged 2 findings · rolled back",
    description: "Migration rolled back pending security review.",
    status: "blocked",
    assigneeLabel: "S",
    assigneeColor: "warning",
    costSoFar: 8.12,
    createdAt: "2026-04-15T11:00:00Z",
  },
  {
    id: "lt-245",
    code: "LT-245",
    title: "Landing page — options strategy explainer",
    subtitle: "Shipped to production · awaiting SEO audit",
    description: "New explainer page for options strategies.",
    status: "done",
    assigneeLabel: "FE",
    assigneeColor: "teal",
    costSoFar: 6.88,
    createdAt: "2026-04-14T10:00:00Z",
  },
];

// ───── Memories ─────
const legacyMemories: Memory[] = [
  {
    id: "m-1",
    title: "Kelly criterion vs modified Sharpe for risk scoring",
    type: "decision",
    content: "Chose modified Sharpe after benchmarking both. Kelly over-weighted recent drawdowns.",
    savedBy: "CEO Agent",
    createdAt: "2026-04-17T15:00:00Z",
    tags: ["profiler", "risk", "architecture"],
  },
  {
    id: "m-2",
    title: "WebSocket flakiness on Safari mobile",
    type: "bug",
    content: "Safari drops idle WebSockets after 60s. Implemented keepalive ping.",
    savedBy: "Frontend Agent",
    createdAt: "2026-04-16T12:00:00Z",
    tags: ["safari", "websocket", "dashboard"],
  },
  {
    id: "m-3",
    title: "Clerk → NextAuth migration aborted",
    type: "decision",
    content: "2 security findings on JWT handling. Revert until Security Agent approves.",
    savedBy: "Salvador",
    createdAt: "2026-04-15T16:00:00Z",
    tags: ["auth", "security", "rollback"],
  },
];

// ───── Companies ─────
export const seedCompanies: Company[] = [
  {
    id: "legacy-traders",
    name: "Legacy Traders",
    slug: "legacy-traders",
    colorHex: "#c26b55",
    industry: "Trading · SaaS",
    status: "active",
    monthlyBudget: 1200,
    monthlySpendMtd: 684,
    openTickets: 12,
    closedTickets: 47,
    activePipelines: 3,
    agents: [
      mkCEO("lt-ceo"),
      mkFrontend("lt-fe"),
      mkBackend("lt-be"),
      mkDevOps("lt-ops"),
      mkQA("lt-qa"),
      mkSecurity("lt-sec"),
      mkSEO("lt-seo"),
    ],
    humans: [salvador, daniel],
    pipelines: [legacyProfilerPipeline],
    issues: legacyIssues,
    memories: legacyMemories,
    keyMetric: { label: "Velocity", value: "↑ 2.3×", sub: "vs solo" },
  },
  {
    id: "multi-topup",
    name: "Multi Topup",
    slug: "multi-topup",
    colorHex: "#4a7a82",
    industry: "SaaS · Custom Software",
    status: "active",
    monthlyBudget: 800,
    monthlySpendMtd: 312,
    openTickets: 4,
    closedTickets: 23,
    activePipelines: 1,
    agents: [mkCEO("mt-ceo"), mkFrontend("mt-fe"), mkBackend("mt-be"), mkQA("mt-qa")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
  },
  {
    id: "mh-home-solutions",
    name: "MH Home Solutions",
    slug: "mh-home-solutions",
    colorHex: "#7ba05b",
    industry: "Home Services · Local",
    status: "attention",
    monthlyBudget: 400,
    monthlySpendMtd: 142,
    openTickets: 7,
    closedTickets: 18,
    activePipelines: 1,
    agents: [mkCEO("mh-ceo"), mkMarketing("mh-mkt"), mkFrontend("mh-fe"), mkSEO("mh-seo"), mkQA("mh-qa")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    keyMetric: { label: "Leads / week", value: "23", sub: "qualified" },
  },
  {
    id: "flagler-bnb",
    name: "Flagler Beach BNB",
    slug: "flagler-bnb",
    colorHex: "#d4a23e",
    industry: "Hospitality · STR",
    status: "active",
    monthlyBudget: 200,
    monthlySpendMtd: 48,
    openTickets: 3,
    closedTickets: 31,
    activePipelines: 0,
    agents: [mkCEO("fb-ceo"), mkConcierge("fb-g", "Guest Concierge"), mkConcierge("fb-h", "Host Assistant")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
    keyMetric: { label: "Occupancy", value: "87%", sub: "next 60d" },
  },
  {
    id: "charge2go",
    name: "Charge2Go",
    slug: "charge2go",
    colorHex: "#c89b5e",
    industry: "EV Infrastructure",
    status: "active",
    monthlyBudget: 600,
    monthlySpendMtd: 268,
    openTickets: 5,
    closedTickets: 14,
    activePipelines: 2,
    agents: [mkCEO("c2g-ceo"), mkFrontend("c2g-fe"), mkBackend("c2g-be"), mkDevOps("c2g-ops"), mkSEO("c2g-seo")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
  },
  {
    id: "minari",
    name: "Minari Solutions",
    slug: "minari",
    colorHex: "#8a6d43",
    industry: "Custom Software",
    status: "active",
    monthlyBudget: 300,
    monthlySpendMtd: 87,
    openTickets: 2,
    closedTickets: 8,
    activePipelines: 1,
    agents: [mkCEO("mn-ceo"), mkBackend("mn-be")],
    humans: [daniel],
    pipelines: [],
    issues: [],
    memories: [],
  },
];

// ───── Approvals ─────
export const seedApprovals: Approval[] = [
  {
    id: "app-1",
    companyId: "legacy-traders",
    companyName: "Legacy Traders",
    type: "hire",
    title: "Hire: Backend Engineer",
    description: "CEO agent requests backend hire for Bryan AI profiler refactor. GPT-5.4 recommended.",
    requesterAgentLabel: "CEO Agent",
    tag: "$400/mo cap",
    createdAt: "2026-04-18T09:15:00Z",
  },
  {
    id: "app-2",
    companyId: "legacy-traders",
    companyName: "Legacy Traders",
    type: "deploy",
    title: "Deploy to production",
    description: "Checkout v2 passed all QA gates. Playwright E2E ✓ · Security scan ✓",
    requesterAgentLabel: "Backend Agent",
    tag: "Legacy Traders",
    createdAt: "2026-04-18T09:40:00Z",
    impact: {
      "Users affected": "1,247 active",
      "QA pass rate": "100%",
      "Rollback ready": "Yes · 15s",
      "Security scan": "Clean",
    },
  },
  {
    id: "app-3",
    companyId: "mh-home-solutions",
    companyName: "MH Home Solutions",
    type: "budget",
    title: "Budget increase request",
    description: "Marketing agent wants +$150/mo for paid lead acquisition experiments.",
    requesterAgentLabel: "Marketing Agent",
    tag: "+$150/mo",
    createdAt: "2026-04-18T08:20:00Z",
  },
  {
    id: "app-4",
    companyId: "charge2go",
    companyName: "Charge2Go",
    type: "spec-review",
    title: "Spec review: EV Station Finder PRD",
    description: "New sub-product PRD ready for your sign-off before pipeline kicks off.",
    requesterAgentLabel: "CEO Agent",
    tag: "Pre-pipeline",
    createdAt: "2026-04-18T10:05:00Z",
  },
];

// ───── Activity stream ─────
export const seedActivityStream: ActivityEntry[] = [
  {
    id: "a-1",
    timestamp: "2026-04-18T10:41:00Z",
    level: "success",
    agentLabel: "Frontend Dev · Sonnet",
    companyName: "Legacy Traders",
    text: "shipped checkout flow v2 to staging",
    meta: "QA verification passed · 1m 24s · $0.42",
  },
  {
    id: "a-2",
    timestamp: "2026-04-18T10:29:00Z",
    level: "warning",
    agentLabel: "Security Advisor · Opus",
    companyName: "Legacy Traders",
    text: "flagged 2 findings on auth refactor",
    meta: "Awaiting your review · 12m ago",
  },
  {
    id: "a-3",
    timestamp: "2026-04-18T10:07:00Z",
    level: "neutral",
    agentLabel: "Interview Agent",
    companyName: "Charge2Go",
    text: "drafted PRD for EV Station Finder Mobile",
    meta: "Converted to Company · ready for kickoff · 34m ago",
  },
  {
    id: "a-4",
    timestamp: "2026-04-18T09:55:00Z",
    level: "success",
    agentLabel: "Guest Concierge",
    companyName: "Flagler BNB",
    text: "replied to 4 Airbnb inquiries in ES + EN",
    meta: "All under 90s response time · $0.06 total",
  },
];

// ───── Threads (Helm Chat) ─────
export const seedThreads: Thread[] = [
  {
    id: "t-ev-finder",
    title: "EV Station Finder",
    role: "interview",
    messages: [
      {
        id: "m1",
        role: "assistant",
        content:
          "¿Qué estás tratando de construir — y para quién duele tanto este problema que lo pagarían hoy?",
        timestamp: "2026-04-18T11:42:00Z",
      },
      {
        id: "m2",
        role: "user",
        content:
          "Los dueños de Teslas en Florida se frustran cuando viajan a zonas nuevas porque los estimados de las apps no consideran elevación, viento ni clima. La gente termina llegando con 4% de batería o manejando 30 millas fuera de ruta a un charger equivocado. Tengo la data de carga de Charge2Go pero necesito un front para dueños de EV, no para operadores de stations.",
        timestamp: "2026-04-18T11:43:00Z",
        attachments: [
          { id: "att-1", type: "pdf", fileName: "charge2go-research.pdf", sizeLabel: "2.4 MB · 18 pages" },
          { id: "att-2", type: "image", fileName: "whiteboard-sketch.jpg", sizeLabel: "1.1 MB · from iPhone" },
        ],
      },
      {
        id: "m3",
        role: "assistant",
        content:
          "Leí el PDF y el sketch. Entiendo tres cosas: es B2C, datos reales de Charge2Go, y la ventaja competitiva es física (weather + elevation), no mejor UI.\n\nAntes de armarte el PRD, dos cosas que definen el stack:",
        timestamp: "2026-04-18T11:43:30Z",
        suggestionGroups: [
          { label: "Form factor", options: ["🚗 Mobile-first (PWA)", "💻 Landing + web app", "📱 Native app (iOS + Android)"] },
          { label: "Timeline", options: ["⚡ MVP en 2 semanas", "🎯 Producto sólido en 6 semanas", "🏗️ Plataforma completa en 12"] },
        ],
        prdPreview: {
          title: "EV Station Finder",
          description:
            "Mobile-first PWA for EV owners in Florida. Real-time range estimates factoring weather, elevation, and live charger availability from the Charge2Go network.",
          stackPills: ["Next.js 15", "Tailwind", "PWA"],
          parentCompany: "Charge2Go (new sub-product)",
          coreFeatures: "Map · Range calc · Weather API · Live availability",
          agentsToHire: "CEO · Frontend · Backend · QA · SEO",
          confidencePercent: 94,
        },
      },
    ],
    createdAt: "2026-04-18T11:42:00Z",
    updatedAt: "2026-04-18T11:43:30Z",
    totalCost: 0.34,
  },
];
